### ISSUE TITLE
APT resolve failure

### ISSUE THREAD

**Issue by faveoled** [jelmer/ognibuild#10]
I tried to compile a CMake project locally which depended on Qt5SVG which is present in my Ubuntu's 20.04 repository but the tool did not propose the correct package. Is it a bug or I'm doing something wrong? Same error with no --resolve option.
```
user@hp-laptop:~/Downloads/kpeg-0.3$ ogni --resolve apt build
Preparing directory .
Using requirement resolver: apt
Detected buildsystems: cmake
Checking that declared requirements are present
Unable to determine declared dependencies from CMake('.')
Running ['cmake', '.', '-Bbuild']
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5Svg" with any
  of the following names:

    Qt5SvgConfig.cmake
    qt5svg-config.cmake

  Add the installation prefix of "Qt5Svg" to CMAKE_PREFIX_PATH or set
  "Qt5Svg_DIR" to a directory containing one of the above files.  If "Qt5Svg"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/user/Downloads/kpeg-0.3/build/CMakeFiles/CMakeOutput.log".
Identified error: CMakeFilesMissing(filenames=['Qt5SvgConfig.cmake', 'qt5svg-config.cmake'], version=None)
Attempting to use fixer upstream requirement fixer(apt) to address CMakeFilesMissing(filenames=['Qt5SvgConfig.cmake', 'qt5svg-config.cmake'], version=None)
Loading apt contents information
Failed to find resolution for error CMakeFilesMissing(filenames=['Qt5SvgConfig.cmake', 'qt5svg-config.cmake'], version=None). Giving up.
```

**Comment by jelmer** [comment]
It's probably a bug - it should be able to find the relevant package in this case since libqt5svg5-dev ships that file: 

```
% apt-file search -x "/usr/lib/.*/cmake/.*/Qt5SvgConfig.cmake"
libqt5svg5-dev: /usr/lib/x86_64-linux-gnu/cmake/Qt5Svg/Qt5SvgConfig.cmake
```

Can you run with --verbose and see what that says?

I've pushed some improvements to ognibuild to suggest follow-up actions.

**Comment by jelmer** [comment]
Does that mean you're running 0.11?

apt-file is optional, but ognibuild won't have to load remote files if it is installed (so it'll be faster).

Can you try running this command:

```
python3 -m ognibuild.debian.file_search -x /usr/lib/.*/cmake/.*/Qt5SvgConfig\\.cmake
```

it should just return

```
libqt5svg5-dev
```

**Comment by faveoled** [comment]
I think it was 0.11 (--version option would be useful to implement though).
Updated from git as you requested:
```
user@hp-laptop:~/Downloads/kpeg-0.3$ python3 -m ognibuild.debian.file_search -x /usr/lib/.*/cmake/.*/Qt5SvgConfig\\.cmake
libqt5svg5-dev
user@hp-laptop:~/Downloads/kpeg-0.3$ ogni --verbose --resolve apt build
Preparing directory .
Using requirement resolver: apt
Detected buildsystems: cmake
Checking that declared requirements are present
Unable to determine declared dependencies from CMake('.')
Running ['cmake', '.', '-Bbuild']
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5Svg" with any
  of the following names:

    Qt5SvgConfig.cmake
    qt5svg-config.cmake

  Add the installation prefix of "Qt5Svg" to CMAKE_PREFIX_PATH or set
  "Qt5Svg_DIR" to a directory containing one of the above files.  If "Qt5Svg"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/user/Downloads/kpeg-0.3/build/CMakeFiles/CMakeOutput.log".
Identified error: CMakeFilesMissing(filenames=['Qt5SvgConfig.cmake', 'qt5svg-config.cmake'], version=None)
Attempting to use fixer upstream requirement fixer(apt) to address CMakeFilesMissing(filenames=['Qt5SvgConfig.cmake', 'qt5svg-config.cmake'], version=None)
Searching for packages containing ['/usr/lib/.*/cmake/.*/Qt5SvgConfig\\.cmake']
Using apt-file to search apt contents
Searching for packages containing ['/usr/lib/.*/cmake/.*/qt5svg\\-config\\.cmake']
Failed to find resolution for error CMakeFilesMissing(filenames=['Qt5SvgConfig.cmake', 'qt5svg-config.cmake'], version=None). Giving up.
Please consider filing a bug report at https://github.com/jelmer/ognibuild/issues/new
```

**Comment by faveoled** [comment]
Before the update I had this:
```
user@hp-laptop:~/Downloads/kpeg-0.3$ python3 -m ognibuild.debian.file_search -x /usr/lib/.*/cmake/.*/Qt5SvgConfig\\.cmake
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/python3.8/site-packages/ognibuild/debian/file_search.py", line 429, in <module>
    sys.exit(main(sys.argv))
  File "/home/user/.local/lib/python3.8/site-packages/ognibuild/debian/file_search.py", line 417, in main
    main_searcher = get_apt_contents_file_searcher(PlainSession())
  File "/home/user/.local/lib/python3.8/site-packages/ognibuild/debian/file_search.py", line 231, in get_apt_contents_file_searcher
    if AptFileFileSearcher.has_cache(session):
  File "/home/user/.local/lib/python3.8/site-packages/ognibuild/debian/file_search.py", line 188, in has_cache
    session.check_call([cls.CACHE_IS_EMPTY_PATH])
  File "/home/user/.local/lib/python3.8/site-packages/ognibuild/session/plain.py", line 75, in check_call
    argv = self._prepend_user(user, argv)
  File "/home/user/.local/lib/python3.8/site-packages/ognibuild/session/plain.py", line 39, in _prepend_user
    raise NoSessionOpen(self)
ognibuild.session.NoSessionOpen: PlainSession()
```

**Comment by jelmer** [comment]
Found the issue - please try the latest snapshot?

**Comment by faveoled** [comment]
Works now, thanks.
