### ISSUE TITLE
thread 'main' panicked at src/session/plain.rs:157

### ISSUE THREAD

**Issue by faveoled** [jelmer/ognibuild#307]
```
headless@quick:~/vnote$ ogni build
Preparing directory /home/headless/vnote/
Running as user, so using user installation scope
Checking that declared dependencies are present
thread 'main' panicked at src/session/plain.rs:157:21:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The problem is that the error doesn't tell what exactly the app wants to find.

ogni v0.0.41

**Comment by jelmer** [comment]
Can you try running with RUST_BACKTRACE=full set?

**Comment by faveoled** [comment]
`--debug` helped me

**Comment by jelmer** [comment]
Did you have cmake installed?

**Comment by faveoled** [comment]
No

**Comment by jelmer** [comment]
In this particular codepath, we should ensure that cmake is installed.

**Comment by jelmer** [comment]
Fixed now.
