### ISSUE TITLE
What distros are / will be supported besides Debian-based?

### ISSUE THREAD

**Issue by yochananmarqos** [jelmer/ognibuild#7]
Commit 7b2f565 makes no sense as the test fails without `dpkg` installed. 

I created an [AUR package](https://aur.archlinux.org/packages/ognibuild) thinking this would be nice to have around for checking dependencies, but it seems I may need to give up and delete it.

**Comment by jelmer** [comment]
The ogni command should be distribution-independent, though it's possible that some Debian-dependencies have leaked in. If you do run into any issues, I'd be grateful for bug reports of e.g. failed test runs.

The deb-fix-build command is (obviously) Debian-specific.

**Comment by yochananmarqos** [comment]
Running `python setup.py test` without `dpkg` results:

```
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing ognibuild.egg-info/PKG-INFO
writing dependency_links to ognibuild.egg-info/dependency_links.txt
writing entry points to ognibuild.egg-info/entry_points.txt
writing requirements to ognibuild.egg-info/requires.txt
writing top-level names to ognibuild.egg-info/top_level.txt
adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
adding license file 'AUTHORS' (matched pattern 'AUTHORS*')
reading manifest file 'ognibuild.egg-info/SOURCES.txt'
writing manifest file 'ognibuild.egg-info/SOURCES.txt'
running build_ext
test_debian_build (unittest.loader._FailedTest) ... ERROR
test_debian_fix_build (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_debian_build (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_debian_build
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/mnt/storage/AUR/ognibuild/src/ognibuild-0.0.7/ognibuild/tests/test_debian_build.py", line 21, in <module>
    from ..debian.build import add_dummy_changelog_entry, get_build_architecture
  File "/mnt/storage/AUR/ognibuild/src/ognibuild-0.0.7/ognibuild/debian/build.py", line 39, in <module>
    from breezy.plugins.debian.builder import BuildFailedError
ModuleNotFoundError: No module named 'breezy.plugins.debian'


======================================================================
ERROR: test_debian_fix_build (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_debian_fix_build
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/mnt/storage/AUR/ognibuild/src/ognibuild-0.0.7/ognibuild/tests/test_debian_fix_build.py", line 33, in <module>
    from ..debian.fix_build import (
  File "/mnt/storage/AUR/ognibuild/src/ognibuild-0.0.7/ognibuild/debian/fix_build.py", line 102, in <module>
    from breezy.plugins.debian.changelog import debcommit
ModuleNotFoundError: No module named 'breezy.plugins.debian'


----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
```

**Comment by jelmer** [comment]
Can you try with the current main branch? I've pushed some more improvements that should make Debian support optional.

**Comment by yochananmarqos** [comment]
Yes, that did the trick. I was able to remove `dpkg`, `python-apt`, `python-debian` and `python-debmutate`. The test succeeds and no errors running it so far.
